# Generated by Django 3.2.7 on 2021-10-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phnumberalt',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
