# Generated by Django 3.2.7 on 2021-10-12 02:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0004_alter_contactinfo_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phnumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phnumberalt',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
