# Generated by Django 3.2.7 on 2021-10-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0005_auto_20211011_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='photo',
            field=models.ImageField(default='contactpics/default.png', upload_to='contactpics'),
        ),
    ]
