# Generated by Django 3.2.7 on 2021-10-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0006_contactinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='contactpics'),
        ),
    ]
