# Generated by Django 3.2.7 on 2021-11-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0011_alter_contactinfo_phnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID'),
        ),
    ]
